simulation: simulation_config.yaml
animats:
- animat_config.yaml
arenas:
- arena_config.yaml
loaders:
  simulation_options: farms_core.simulation.options.SimulationOptions
  animats_options:
  - cmc_controllers.neural_options.NeuralOptions
  arenas_options:
  - farms_amphibious.model.options.AmphibiousArenaOptions
  experiment_data: farms_amphibious.data.data.AmphibiousExperimentData
  animats_data:
  - cmc_controllers.neural_data.NeuralData